name: vigilancia_app
description: Aplicación Android para ver la cámara de otro teléfono en la misma red Wi-Fi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_info_plus: ^13.2.0
  flutter_webrtc: ^1.6.2+hotfix.3
  permission_handler: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - icon.png
